### PR TITLE
Update logger/notifier and fix wording

### PR DESCRIPTION
**Pull request by PuKoren**
Update of Guidelines:
- Usage of `@dialonce/boot` for logger/notifier instead of winston/bugsnag
- Sample code can be put in README
- Fix wording on dynamically linked c++ modules for native npm and docker image

Reviewers: @dial-once/developers

### CODE REVIEW

**Comment by mrister** [comment]
LGTM

**Comment by jkernech** [comment]
LGTM ❤️

**Comment by ykhatal** [comment]
LGTM

**Comment by ykhatal** [comment]
@PuKoren I can't remove myself from the assignees, i think I'm not allowed

**Pull request merged**
