### PR TITLE
Makefile instructions

### PR DESCRIPTION
**Pull request by PuKoren**
For @dial-once/developers

### CODE REVIEW

**Comment by jkernech** [comment]
We could also mention the coding style, e.g http://clarkgrubb.com/makefile-style-guide

**Comment by mrister** [comment]
LGTM

**Comment by mrister** [comment]
cannot un assign on this one

**Comment by ykhatal** [comment]
LGTM

**Comment by ykhatal** [comment]
@PuKoren can't remove myself from assignees, no right for

**Comment by jkernech** [comment]
@PuKoren What about the coding style of the Makefile ?

**Comment by PuKoren** [comment]
@jkernech TBH it was so long I didn't read all of it, and considering our usage of Make I would not ask for anyone to fully acknowledge it, I guess we could put it as a reference but not a requirement. What do you think guys?

**Comment by jkernech** [comment]
@PuKoren I agree with you that we can put a reference on this article or on another one more concise

**Comment by mrister** [comment]
agreed

**Comment by PuKoren** [comment]
Reference added

**Review by jkernech — APPROVED** [review]

**Pull request merged**
